openapi: 3.0.1
info:
  title: Gnosis RAG Plugin
  description: A plugin for indexing, saving conversations, and querying an Obsidian vault using RAG (Retrieval-Augmented Generation)
  version: 'v1'
servers:
  - url: YOUR_CLOUDFLARE_TUNNEL_URL
paths:
  /index:
    post:
      operationId: indexDocuments
      summary: Index documents in the Obsidian vault
      description: Index all documents in the Obsidian vault for improved search and retrieval
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                force:
                  type: boolean
                  description: Force re-indexing of all documents
                  default: false
                batch_size:
                  type: integer
                  description: Number of documents to process in each batch
                  default: 50
      responses:
        "200":
          description: Indexing completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  documents_indexed:
                    type: integer
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string

  /save:
    post:
      operationId: saveContent
      summary: Save conversation or content to Obsidian vault
      description: Save conversation messages or raw content to the current day's page in the Obsidian vault
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - conversation_name
              properties:
                conversation_name:
                  type: string
                  description: Name/title for the saved content
                session_id:
                  type: string
                  description: Session ID for conversation-based saving (optional)
                messages:
                  type: array
                  description: Direct messages to save (optional)
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                      content:
                        type: string
                content:
                  type: string
                  description: Raw content to save directly (optional)
      responses:
        "200":
          description: Content saved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  file_path:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string

  /query:
    get:
      operationId: queryVault
      summary: Query the Obsidian vault
      description: Search and retrieve relevant information from the indexed Obsidian vault using RAG
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: The search query
        - in: query
          name: limit
          schema:
            type: integer
            default: 5
          description: Maximum number of results to return
        - in: query  
          name: similarity_threshold
          schema:
            type: number
            default: 0.7
          description: Minimum similarity threshold for results
      responses:
        "200":
          description: Query results
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  answer:
                    type: string
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                        metadata:
                          type: object
                        score:
                          type: number
                  total_results:
                    type: integer
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string 