version: '3.8'

services:
  postgres:
    image: ankane/pgvector:v0.5.0
    environment:
      POSTGRES_USER: gnosis_user
      POSTGRES_PASSWORD: gnosis_pass
      POSTGRES_DB: gnosis_rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gnosis_user -d gnosis_rag"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+asyncpg://gnosis_user:gnosis_pass@postgres:5432/gnosis_rag
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-test-key}
      - OPENAI_MODEL=gpt-4o-mini
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small
      - DEBUG=true
      - LOG_LEVEL=INFO
      - RATE_LIMIT_REQUESTS=30
      - RATE_LIMIT_PERIOD=60
      - GRAPH_MAX_HOPS=2
      - GRAPH_MAX_DOCUMENTS=10
      - GRAPH_WEIGHT_VECTOR=0.6
      - GRAPH_WEIGHT_GRAPH=0.4
      - EMBEDDING_DIMENSION=1536
      - SIMILARITY_THRESHOLD=0.7
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: 