# Obsidian Vault Configuration
vault:
  path: ${OBSIDIAN_VAULT_PATH}
  exclude_folders: ["templates", ".trash", ".git"]
  file_extensions: [".md"]

# Embedding Configuration
embeddings:
  provider: ${EMBEDDING_PROVIDER}  # "openai" or "local"
  model: ${EMBEDDING_MODEL}  # for OpenAI
  local_model: ${LOCAL_MODEL}  # for local embeddings
  batch_size: 32
  max_tokens: 8191

# Vector Store Configuration
vector_store:
  type: "faiss"  # or "chroma" or "qdrant"
  dimension: 1536  # 1536 for OpenAI, 384 for all-MiniLM
  index_path: ${VECTOR_STORE_PATH}
  similarity_metric: "cosine"

# Text Processing
chunking:
  chunk_size: 512
  chunk_overlap: 50
  split_by: "paragraph"  # or "sentence"

# API Configuration
api:
  host: ${API_HOST}
  port: ${API_PORT}
  debug: ${DEBUG_MODE}

# Logging
logging:
  level: "INFO"
  file: "logs/gnosis.log" 